// Generated by CoffeeScript 1.4.0
(function() {

  exports.parsy = function() {
    var opt, options;
    options = {};
    opt = null;
    process.argv.forEach(function(arg) {
      if (/^(-|--)/.test(arg) || !opt) {
        if (!/\w/.test(arg)) {
          return;
        }
        opt = arg;
        return options[opt] = true;
      } else {
        if (arg === 'false') {
          arg = false;
        } else if (arg === 'true') {
          arg = true;
        } else {
          if (!isNaN(arg)) {
            arg = Number(arg);
          }
        }
        if (typeof options[opt] === 'boolean') {
          return options[opt] = arg;
        } else if (Array.isArray(options[opt])) {
          return options[opt].push(arg);
        } else {
          return options[opt] = [options[opt], arg];
        }
      }
    });
    return {
      options: options,
      on: function(opt, callback) {
        if (options[opt] != null) {
          return callback(opt, options[opt]);
        }
      }
    };
  };

}).call(this);
